import { postRequest } from 'util/fetch'

export const login = data => postRequest('/account/login.shtml', { ...data })
export const checkUserName = (username, isShow = true) => postRequest('/account/checkUserName.shtml', { username }, true, isShow)
export const getCode = phone => postRequest('/account/sendVerifyCode.shtml', { phone })
export const registered = data => postRequest('/account/register.shtml', { ...data })
export const resetUserPass = data => postRequest('/account/resetUserPass.shtml', { ...data })
export const verification = data => postRequest('/account/checkVerifyCode.shtml', { ...data })
export const update = data => postRequest('/device/update.shtml', { ...data }, false)
export const account = data => postRequest('/account/setTradePass.shtml', { ...data })
export const accountData = () => postRequest('/account/getData.shtml')
export const forgetTradePass = data => postRequest('/account/forgetTradePass.shtml',{...data})
export const resetTradePass = data => postRequest('/account/resetTradePass.shtml', { ...data })
export const etWalletAddress = () => postRequest('/wallet/getWalletAddress.shtml')
export const addOrder = data => postRequest('/order/addOrder.shtml', { ...data }, false)
export const checkTradePass = data => postRequest('/account/checkTradePass.shtml',{ ...data }, false)
export const getOrders = () => postRequest('/order/getOrders.shtml')
export const addWalletAddress = data => postRequest('/wallet/addWalletAddress.shtml',{...data})
export const deleteWalletAddress = id => postRequest('/wallet/deleteWalletAddress.shtml',{id})
export const updateWalletAddress = data => postRequest('/wallet/updateWalletAddress.shtml',{...data})
export const checkExistsPhone = phone => postRequest('/account/checkExistsPhone.shtml',{phone})
export const getUserNameForPhone = data => postRequest('/account/getUserNameForPhone.shtml',{...data})
export const getVerifyCode = data => postRequest('/account/sendVerifyCode.shtml', { ...data })
